### ISSUE TITLE
error -32603: this project is not configured to be accessed by an LLM

### ISSUE THREAD

**Issue by cocodrino** [nhost/mcp-nhost#20]
👋 Hi again! I've been using Nhost's MCP with great results recently. However, after switching projects, I'm encountering some issues replicating the same success. I reconfigured the setup with something like this:

```toml

[cloud]
pat = '6d0cf57b-ce68-477c-9d2b-db34xxxxx'
enable_mutations = true

[local]
admin_secret = 'nhost-admin-secret'

[[projects]]
subdomain = 'ypvcdgqqrqsgxxxxx'
region = 'us-east-1'
admin_secret = 'Ku-5rUvTaiwjcU7(Xk5UIxxxxx'
allow_queries = ['*']
allow_mutations = ['*']


```

Basic queries like this work fine:

```bash
echo '{"jsonrpc":"2.0","method":"tools/call","params":{"name":"cloud-graphql-query","arguments":{"query":"{ apps { id subdomain name } }"}},"id":1}' | mcp-nhost start
```

But when trying to fetch table data or schema information, I get:

`Error: MCP error -32603: this project is not configured to be accessed by an LLM`

This worked flawlessly in my previous project. Do I need additional configuration? Also:

Where exactly do I get the "project PAT"? (I'm currently using the admin secret - which worked fine before)

Are there specific permissions I need to enable for LLM access?

Thanks for your help!
